apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-image-to-quay
spec:
  resources:
    inputs:
      - name: image
        type: image
  params:
    - default: my-quay-account
      description: The quay.io account that matches the credentials stored in the mounted secret.
      name: quay-io-account
      type: string
    - default: quay.io/my-quay-account/my-quay-repo
      description: The quay.io repository in which to store the image.
      name: quay-io-repository
      type: string
    - description: 'URL of container image to be built, i.e. output path'
      name: qotd-image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/pipelines-rheledge/appname:latest
    - default: $(inputs.params.quay-io-image-tag-name)
      description: The tag to use to identify the image.
      name: quay-io-image-tag-name
      type: string
    - default: overlay
      description: The Buildah storage STORAGE_DRIVER
      name: STORAGE_DRIVER
      type: string
    - name: pvcname
      type: string
      description: The name of the PVC to use
      default: shared-workspace-pvc
  steps:
    - command:
        - podman
        - pull
        - '--tls-verify=false'
        - $(params.params.qotd-image)
      image: registry.redhat.io/rhel8/podman
      name: podman-pull-image
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: pipeline-cache
    - command:
        - buildah
        - tag
        - '--storage-driver=$(params.STORAGE_DRIVER)'
        - $(params.params.qotd-image))
        - '$(params.quay-io-repository):$(params.quay-io-image-tag-name)'
      image: registry.redhat.io/rhel8/buildah
      name: buildah-tag-image
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: pipeline-cache
    - command:
        - buildah
        - images
        - '--storage-driver=$(params.STORAGE_DRIVER)'
      image: registry.redhat.io/rhel8/buildah
      name: buildah-list-images-after-tagging
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: pipeline-cache
    - command:
        - buildah
        - push
        - '--tls-verify=false'
        - '--storage-driver=$(params.STORAGE_DRIVER)'
        - '--authfile'
        - /etc/secret-volume/.dockerconfigjson
        - '$(params.quay-io-repository):$(params.quay-io-image-tag-name)'
      image: registry.redhat.io/rhel8/buildah
      name: push-image-to-quay
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /etc/secret-volume
          name: quay-auth-secret
          readOnly: true
        - mountPath: /var/lib/containers
          name: pipeline-cache
      workingDir: /quay
  volumes:
    - name: quay-auth-secret
      secret:
        secretName: quay-auth-secret
    - name: pipeline-cache
      persistentVolumeClaim:
        claimName:  $(params.pvcname)
