apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: pipeline-scc
  namespace: pipelines-rheledge
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: RunAsAny
users:
- system:serviceaccount:pipelines-rheledge:pipeline